---
# Install necessary packages for Docker, add GPG key, and add repository

# Install necessary packages for Docker
- name: Install necessary packages for Docker
  apt:
    name:
      - ca-certificates
      - curl
    state: present

# Add Docker's GPG key
- name: Create directory for Docker GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

# Add Docker repository
- name: Add Docker repository to sources list
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" > /etc/apt/sources.list.d/docker.list
  args:
    creates: /etc/apt/sources.list.d/docker.list

# Update apt package index after adding Docker repository
- name: Update apt package index after adding Docker repository
  apt:
    update_cache: yes
