---

- name: Copy service account key to temporary directory
  copy:
    src: "{{ local_service_account_key }}"
    dest: "{{ remote_service_account_key }}"
    mode: '0600'

- name: Authenticate with service account
  command: gcloud auth activate-service-account --key-file={{ remote_service_account_key }}
  register: auth_result
  failed_when: auth_result.rc != 0

- name: Remove temporary key file
  file:
    path: "{{ remote_service_account_key }}"
    state: absent
  become: yes

- name: Check gcloud authentication status
  command: gcloud auth list
  register: auth_list_result
  ignore_errors: yes

- debug:
    msg: "{{ auth_list_result.stdout_lines }}"

- name: Configure Docker to use gcloud credentials
  command: gcloud auth configure-docker asia-east1-docker.pkg.dev
  register: configure_docker_result
  failed_when: configure_docker_result.rc != 0
